# Enables support for a docker container-based build,
# see: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install tox tox-travis
script:
  - tox -v
